package com.htzw.study.entities;

public class Organization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.org_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.org_name
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.parent_org_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private Integer parentOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.org_code
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.leaf
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private Boolean leaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.status
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org.update_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.org_id
     *
     * @return the value of org.org_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.org_id
     *
     * @param orgId the value for org.org_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.org_name
     *
     * @return the value of org.org_name
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.org_name
     *
     * @param orgName the value for org.org_name
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.parent_org_id
     *
     * @return the value of org.parent_org_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public Integer getParentOrgId() {
        return parentOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.parent_org_id
     *
     * @param parentOrgId the value for org.parent_org_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setParentOrgId(Integer parentOrgId) {
        this.parentOrgId = parentOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.org_code
     *
     * @return the value of org.org_code
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.org_code
     *
     * @param orgCode the value for org.org_code
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.leaf
     *
     * @return the value of org.leaf
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public Boolean getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.leaf
     *
     * @param leaf the value for org.leaf
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setLeaf(Boolean leaf) {
        this.leaf = leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.status
     *
     * @return the value of org.status
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.status
     *
     * @param status the value for org.status
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org.update_date
     *
     * @return the value of org.update_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org.update_date
     *
     * @param updateDate the value for org.update_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }
}