package com.htzw.study.entities;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.true_name
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String trueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role_type
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.org_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.stauts
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private Integer stauts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.remark
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.true_name
     *
     * @return the value of user.true_name
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.true_name
     *
     * @param trueName the value for user.true_name
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName == null ? null : trueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role_type
     *
     * @return the value of user.role_type
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role_type
     *
     * @param roleType the value for user.role_type
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.org_id
     *
     * @return the value of user.org_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.org_id
     *
     * @param orgId the value for user.org_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.stauts
     *
     * @return the value of user.stauts
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public Integer getStauts() {
        return stauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.stauts
     *
     * @param stauts the value for user.stauts
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setStauts(Integer stauts) {
        this.stauts = stauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_date
     *
     * @return the value of user.update_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_date
     *
     * @param updateDate the value for user.update_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.remark
     *
     * @return the value of user.remark
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.remark
     *
     * @param remark the value for user.remark
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}