package com.htzw.study.entities;

public class WorkLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log.work_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private Integer workId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log.work_content
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String workContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log.start_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log.end_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log.project_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log.user_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log.status
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log.work_summary
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String workSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log.year
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log.month
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log.week
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    private String week;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log.work_id
     *
     * @return the value of work_log.work_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log.work_id
     *
     * @param workId the value for work_log.work_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log.work_content
     *
     * @return the value of work_log.work_content
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getWorkContent() {
        return workContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log.work_content
     *
     * @param workContent the value for work_log.work_content
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setWorkContent(String workContent) {
        this.workContent = workContent == null ? null : workContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log.start_date
     *
     * @return the value of work_log.start_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log.start_date
     *
     * @param startDate the value for work_log.start_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log.end_date
     *
     * @return the value of work_log.end_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log.end_date
     *
     * @param endDate the value for work_log.end_date
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log.project_id
     *
     * @return the value of work_log.project_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log.project_id
     *
     * @param projectId the value for work_log.project_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log.user_id
     *
     * @return the value of work_log.user_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log.user_id
     *
     * @param userId the value for work_log.user_id
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log.status
     *
     * @return the value of work_log.status
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log.status
     *
     * @param status the value for work_log.status
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log.work_summary
     *
     * @return the value of work_log.work_summary
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getWorkSummary() {
        return workSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log.work_summary
     *
     * @param workSummary the value for work_log.work_summary
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setWorkSummary(String workSummary) {
        this.workSummary = workSummary == null ? null : workSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log.year
     *
     * @return the value of work_log.year
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log.year
     *
     * @param year the value for work_log.year
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log.month
     *
     * @return the value of work_log.month
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log.month
     *
     * @param month the value for work_log.month
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log.week
     *
     * @return the value of work_log.week
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log.week
     *
     * @param week the value for work_log.week
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    public void setWeek(String week) {
        this.week = week == null ? null : week.trim();
    }
}