package com.htzw.study.dao;

import com.htzw.study.entities.Organization;
import java.util.List;

public interface OrganizationMapper {

    int deleteByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    Organization selectByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    List<Organization> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    int updateByPrimaryKey(Organization record);
}