package com.htzw.study.dao;

import com.htzw.study.entities.Project;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
/**
* @Description:    java类作用描述
* @Author:         glj
* @CreateDate:     2018/9/28 10:28
* @Version:        1.0
*/
@Mapper
public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    int deleteByPrimaryKey(Integer projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    Project selectByPrimaryKey(Integer projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    List<Project> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Fri Sep 28 10:18:38 CST 2018
     */
    int updateByPrimaryKey(Project record);
}